#!/bin/sh
### BEGIN INIT INFO
# Provides:          thinkd
# Required-Start:    acpid
# Required-Stop:     
# X-Start-Before:    kdm gdm xdm
# X-Stop-After:      kdm gdm xdm
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: Start the thinkd daemon
# Description:       power management daemon for thinkpad laptops
### END INIT INFO

set -e

THINKD="/usr/local/bin/thinkd"
PIDFILE="/var/run/thinkd.pid"

# Check for daemon presence
[ -x "$THINKD" ] || exit 0

# Get lsb functions
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting THINKD service..."
    start-stop-daemon --start --quiet --pidfile "$PIDFILE" --exec "$THINKD"
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping THINKD service..."
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE" --exec "$THINKD"
    log_end_msg $?
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  reload|force-reload) 
    log_begin_msg "Reloading THINKD service..."
    # in progress
    #  start-stop-daemon --stop --signal 1 --exec "$THINKD"
    log_end_msg $?
    ;;
  status)
    status_of_proc "$THINKD" thinkd
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/thinkd {start|stop|restart|reload|force-reload|status}"
    exit 1
esac

